name: cypher-weather-app

services:
  backend:
    container_name: wapp-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}           # cypher
      DB_PASSWORD: ${DB_PASSWORD}   # cypher-password
      DB_NAME: ${DB_NAME}           # weather_app
      API_KEY: ${API_KEY}           # 1234567890
      USE_CORS: "false"
    expose:
      - 3000
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - internal-net

  frontend:
    container_name: wapp-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
    env_file: .env
    depends_on:
      - backend
    networks:
      - public-net
      - internal-net

  mariadb:
    image: mariadb
    container_name: wapp-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}   # Set the root password
      MARIADB_DATABASE: ${DB_NAME}                 # (Optional) Create a default database
      MARIADB_USER: ${DB_USER}                     # (Optional) Create a default user
      MARIADB_PASSWORD: ${DB_PASSWORD}             # (Optional) Set the default user's password
    volumes:
      - /home/cypherbest/development/maria-persistent:/var/lib/mysql:Z
    ports:
      - 3306:3306
    networks:
      - public-net
      - internal-net

volumes:
  mariadb-data:

networks:
  public-net:
    driver: bridge
  internal-net:
